simplify script

diff --git a/bin/ts b/bin/ts
--- a/bin/ts
+++ b/bin/ts
@@ -1,300 +1,76 @@
 #!/bin/sh
-############################################################################
+
 ts_progname="${0##*/}"
-ts_author="Simon Chiang"
 ts_version="2.0.1"
-ts_release_date="2015-11-04"
 ts_url="http://github.com/thinkerbot/ts"
 
 ts_usage () {
-if [ ts = "$ts_progname" ]
-then ts_argstr="[TEST_FILES...]"
-else ts_argstr="[TEST_NAMES...]"
-fi
-printf "\
-usage: ts [-acdehmrsvw] [-t TS_TMP_DIR] %s
+  if [ "$ts_progname" = ts ]; then
+    ts_arg_expr="[TEST_FILES...]"
+  else
+    ts_arg_expr="[TEST_NAMES...]"
+  fi
+  printf "\
+usage: ts [-dhkv] [-t TS_TMP_DIR] %s
 
-  Tests shell scripts.  Options control the output format.  Artifacts are
-  written to the tmp dir and can be removed with the -r flag.  To debug
-  a failing test try running it with -e to see how it would look if you
-  executed the script in a shell manually (after which you can check exit
-  status as normal), or by using the -d flag to trace execution.
+  Tests shell scripts.
 
     ts test/script*             # run multiple test scripts
     ./test/script               # run a single test script
     ./test/script test_a        # run a single test
-    ./test/script -e test_a     # execute a test as a script
-
-  See \`man ts\` for writing test scripts.
 
 options:
 
-    -a   show all tests
-    -c   color output
-    -d   debugger output
-    -e   exec test
-    -h   prints this help
-    -m   monitor output
-    -q   quiet output (hide stderr)
-    -r   remove tmp dir (rm -r)
-    -s   stream output (implies -a)
-    -t   set the tmp dir (default tmp)
-    -v   verbose output (show stderr, default on)
-    -w   raw output
+    -d  debug output
+    -h  print this help
+    -k  keep tmp dir
+    -t  set the tmp dir (default tmp)
+    -v  verbose output
 
 version: %s - %s
-" "$ts_argstr" "$ts_version" "$ts_url"
+" "$ts_arg_expr" "$ts_version" "$ts_url"
 }
 
-OPTIND=1
-ts_args=""
-while [ $OPTIND -le $# ]
-do
-  ts_optcur="$OPTIND"
-  if getopts "acdehmqrst:vw" ts_option
-  then
-    case "$ts_option" in
-      (a) TS_FILTER=false ;;
-      (c) TS_COLOR=true ;;
-      (d) TS_DEBUG=true; TS_MODE=verbose ;;
-      (e) TS_REPORT=execute ;;
-      (h) ts_usage
-          exit 0 ;;
-      (m) TS_REPORT=monitor ;;
-      (q) TS_MODE=quiet ;;
-      (r) TS_REMOVE_TMP_DIR=true ;;
-      (s) TS_REPORT=stream; TS_FILTER=false ;;
-      (t) TS_TMP_DIR=$OPTARG ;;
-      (v) TS_MODE=verbose ;;
-      (w) TS_REPORT=raw ;;
-      (*) ts_usage | head -n 1
-          exit 2 ;;
-    esac
-  else
-    if [ $OPTIND -gt $ts_optcur ]
-    then ts_optcur="$#"
-    fi
-    while [ $OPTIND -le $ts_optcur ]
-    do
-      ts_args="$ts_args \"\${$OPTIND}\""
-      OPTIND=$(($OPTIND + 1))
-    done
-  fi
+while getopts "dehkt:v" ts_option; do
+  case "$ts_option" in
+    d) TS_DEBUG=1; TS_VERBOSE=1 ;;
+    h) ts_usage
+       exit 0 ;;
+    k) TS_KEEP_TMP_DIR=1 ;;
+    t) TS_TMP_DIR=$OPTARG ;;
+    v) TS_VERBOSE=1 ;;
+    *) ts_usage | head -n 1
+       exit 2 ;;
+  esac
 done
-eval set -- $ts_args
+shift $((OPTIND - 1))
 
-TS_USR_DIR="${TS_USR_DIR:-$(pwd)}"
+TS_USR_DIR="${TS_USR_DIR:-$PWD}"
 TS_TMP_DIR="${TS_TMP_DIR:-$TS_USR_DIR/tmp}"
 
-TS_COLOR=${TS_COLOR:-false}
-TS_DEBUG=${TS_DEBUG:-false}
-TS_FILTER=${TS_FILTER:-true}
-TS_REPORT=${TS_REPORT:-monitor}
-TS_MODE=${TS_MODE:-verbose}
-TS_REMOVE_TMP_DIR=${TS_REMOVE_TMP_DIR:-false}
-
-TS_PASS="${TS_PASS:-[32m}"
-TS_FAIL="${TS_FAIL:-[1;31m}"
-TS_NORM="${TS_NORM:-[0m}"
-TS_SKIP="${TS_SKIP:-[1;33m}"
-
-mkdir -p "$TS_TMP_DIR"
-ts_status_file="$TS_TMP_DIR/status"
-ts_monitor_file="$TS_TMP_DIR/monitor"
-ts_skip_file="$TS_TMP_DIR/skips"
-
-if [ execute = "$TS_REPORT" ] && [ ts = "$ts_progname" ]
-then
-  printf -- "error: -e can only be used when executing test scripts directly\n" >&2
-  exit 1
-fi
-############################################################################
 # private functions
+###############################################################################
 
-# On Ubuntu awk is actually mawk, which does not fflush output but will
-# unbuffer with an option. Detect when that option must be used here.
-# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=593504
-ts_guess_awk_opts () {
-  if awk -Winteractive <&- >/dev/null 2>&1
-  then printf -- "%s\n" -Winteractive
-  fi
-}
-export ts_awk_opts="${ts_awk_opts:-$(ts_guess_awk_opts)}"
-
-# Creates a pattern for use by ts_list.  Example:
-#
-#   ts_pattern a b c     # => "a|b|c"
-#
-ts_pattern () {
-  if [ 0 -ne $# ]
-  then
-    printf "%s" "$1"
-    shift 1
-
-    if [ 0 -ne $# ]
-    then printf "|%s" "$@"
-    fi
-  fi
-}
-
-# Prints all functions in a test file starting with 'test_' or the pattern
-# given by ts_test_pattern.  Recurses into sourced files if TS_TESTS_IN_SOURCE
-# is set to true.
+# Prints all functions in a test file starting with 'test_' or $ts_test_pattern.
 ts_list () {
-  ts_file="$1"
+  local ts_file="$1"
   shift 1
-
-  if [ $# -eq 0 ]
-  then
-    grep -onE "^[[:space:]]*(${ts_test_pattern:-test_\w+})[[:space:]]*\(\)" /dev/null "$ts_file" |
+  local ts_test_pattern=$(printf "$*" | tr " " "|")
+  grep -onE "^[[:space:]]*(${ts_test_pattern:-test_\w+})[[:space:]]*\(\)" /dev/null "$ts_file" |
     sed -e 's/^\([^:]*\):\([0-9]\{1,\}\):[[:space:]]*\([^ (]\{1,\}\).*/\3 \1:\2/'
-  else
-    ts_list "$@" | awk -v file="$ts_file" '{ $2=file " -> " $2; print }'
-  fi
 }
 
-# Converts the ts raw format into the ts stream format.
-ts_stream () {
-  rm "$ts_status_file" 2>/dev/null
-  awk $ts_awk_opts -v status_file="$ts_status_file" '
-function readbytes (bytes) {
-  # ignore current line
-  $0=""
-
-  # play a trick so bytes does not reset the var upon
-  # getline (issue with alpine + gawk)
-  bytes=bytes
-
-  # read bytes
-  while(getline == 1 && (bytes -= length($0) + 1) > 0) {
-    print "  " $0
-  }
-
-  if(length($0) > 0) {
-    print "  " substr($0, 1, bytes + length($0) + 1)
-    $0=""
-  }
-}
-function format (status, descr, bytes) {
-  printf("%s %s\n", status, descr)
-  readbytes(bytes)
-  printf("\n")
-}
-BEGIN { npass=nskip=nfail=0 }
-/^\[/ { descr=$0 }
-/^P/  { format("P", descr, $2); fflush(); npass++; }
-/^F/  { format("F", descr, $2); fflush(); nfail++; }
-/^S/  { format("S", descr, $2); fflush(); nskip++; }
-END   { printf("%d %d %d\n", npass, nfail, nskip) >> status_file }
-'
-}
-
-# Converts the ts stream format into the monitor format.
-ts_monitor () {
-  rm "$ts_monitor_file" 2> /dev/null
-  awk $ts_awk_opts -v "monitor_file=$ts_monitor_file" '
-    BEGIN { ORS = "" };
-    { print $0 "\n" >> monitor_file };
-    /^P/ { print "."; fflush() };
-    /^F/ { print "F"; fflush() };
-    /^S/ { print "-"; fflush() };
-  ' >&2
-  printf "\n\n" >&2
-
-  cat "$ts_monitor_file"
-}
-
-# Filters passing tests from the ts stream format.
-ts_filter () {
-  if [ true = "$TS_FILTER" ]
-  then awk $ts_awk_opts '/^[FS] /,/^$/ { print $0; fflush(); }'
-  else cat
-  fi
-}
-
-# Adds color to the ts stream format.
-ts_color () {
-  if [ true = "$TS_COLOR" ]
-  then awk $ts_awk_opts -v norm="$TS_NORM" -v pass="$TS_PASS" -v skip="$TS_SKIP" -v fail="$TS_FAIL" '
-    /^P / { sub("P [[]", "[" pass); sub("]", norm "]"); }
-    /^F / { sub("F [[]", "[" fail); sub("]", norm "]"); }
-    /^S / { sub("S [[]", "[" skip); sub("]", norm "]"); }
-    { print $0; fflush(); }'
-  else cat
-  fi
-}
-
-# Converts ts stream to color (if specified) or to the report format.
-ts_format () {
-  if [ true = "$TS_COLOR" ]
-  then ts_color
-  else awk $ts_awk_opts '
-    /^[PFS] / { status=$1; sub(". ", ""); }
-    /^$/      { print status; }
-    { print $0; fflush(); }'
-  fi
-}
-
-# Prints the summary for the tests and returns with the correct status.
-ts_print_status () {
-  awk -v nsec="$1" '
-BEGIN { npass=nskip=nfail=0 }
-      { npass += $1; nfail+= $2; nskip += $3; }
-END   { printf("%d pass %d fail %d skip %d s\n", npass, nfail, nskip, nsec); if(nfail > 0) exit 1 }
-' < "$ts_status_file"
-
-  ts_exitstatus=$?
-
-  if [ "true" = "$TS_REMOVE_TMP_DIR" ]
-  then rm -r "$TS_TMP_DIR"
-  fi
-
-  return $ts_exitstatus
-}
-
-ts_report () {
-  case "$TS_REPORT" in
-    (execute)
-      cat
-      exit $(cat "$ts_status_file")
-      ;;
-    (monitor)
-      ts_start_time=${SECONDS:-1}
-      ts_stream | ts_monitor | ts_filter | ts_format
-      ts_end_time=${SECONDS:-0}
-      ts_print_status "$(($ts_end_time - $ts_start_time))" >&2
-      ;;
-    (stream)
-      ts_stream | ts_filter | ts_color
-      ts_print_status > /dev/null
-      ;;
-    (raw)
-      cat
-      ;;
-  esac
-}
-
-# Runs a specific test.  In that case the test output is not filtered or
-# changed. the exit status is the exit status of the specific test.
+# Runs a specific test.
 ts_run_test () {
-  if [ -e "$ts_test_dir" ] && ! rm -r "$ts_test_dir"
-  then
-    printf "could not remove existing test dir: %s\n" "$ts_test_dir"
-    exit 1
-  fi
-
-  if [ -e "$ts_skip_file" ] && ! rm "$ts_skip_file"
-  then
-    printf "could not remove skip file: %s\n" "$ts_skip_file"
-    exit 1
-  fi
+  local ts_test_name="$1"
 
   # input /dev/null so that tests which read from stdin will not hang
   exec </dev/null
 
-  if [ true = "$TS_DEBUG" ]
-  then set -ux
-  else set -u
+  if [ "$TS_DEBUG" ]; then
+    set -ux
+  else
+    set -u
   fi
 
   trap 'teardown' EXIT
@@ -305,129 +81,100 @@ ts_run_test () {
 }
 
 ts_run_test_suite () {
-  ts_test_file="$0"
-  ts_test_case="${ts_test_file##*/}"
+  local ts_test_file="$0"
+  local ts_test_case="${ts_test_file##*/}"
   ts_test_case="${ts_test_case%\.*}"
-  ts_test_pattern="$(ts_pattern "$@")"
-  ts_test_files="${ts_test_files:-$ts_test_file}"
 
-  printf "%s\n" "$ts_test_files" |
-  sed -e '/^[[:space:]]*$/d' |
-  while read ts_test_file
-  do
-    IFS=:
-    ts_list $ts_test_file
-  done |
-  while read ts_test_name ts_test_desc
-  do
-    ts_test_dir="$TS_TMP_DIR/$ts_test_case/$ts_test_name"
-    printf "[%s] %s\n" "$ts_test_desc" "$ts_test_name"
+  local ts_case_dir="$TS_TMP_DIR/$ts_test_case"
+  if ! rm -rf "$ts_case_dir"; then
+    echo "error: could not clean existing test dir: $ts_case_dir"
+    exit 1
+  fi
 
-    if [ execute = "$TS_REPORT" ]
-    then
-      (ts_run_test)
-      printf "%s\n" "$?" > "$ts_status_file"
+  ts_list "$ts_test_file" "$@" |
+  while read ts_test_name ts_test_desc; do
+
+    TS_TEST_DIR="$ts_case_dir/$ts_test_name"
+    mkdir -p "$TS_TEST_DIR"
+
+    # run the test by calling back into the test file
+    # use a subprocess to prevent leakage (eg set -x)
+    # use stdout for progress, stderr for debug information
+    if [ "$TS_VERBOSE" ]; then
+      (ts_run_test $ts_test_name >/dev/null)
     else
-
-      # run the test by calling back into the test file
-      # * use stdout for progress, stderr for debug information
-      # * a zero exit status is considered a pass, otherwise fail
-      # * capture as a variable to calculate length
-      # * use a subprocess to prevent leakage (ex set -x)
-      if ts_stdout=$(
-        if [ verbose = "$TS_MODE" ]
-        then (ts_run_test 2>&1)
-        else (ts_run_test 2>/dev/null)
-        fi
-        )
-      then
-        if [ -e "$ts_skip_file" ]
-        then ts_status=S
-        else ts_status=P
-        fi
-      else
-        ts_status=F
-      fi
-
-      printf "%s %d\n%s\n" "$ts_status" "${#ts_stdout}" "$ts_stdout"
+      (ts_run_test $ts_test_name >/dev/null 2>&1)
     fi
-  done | ts_report
-}
-
-ts_src_test_files () {
-  shift 1
-  for ts_test_file in "$@"
-  do
-    ts_prev="${ts_curr:-$0}"
-    ts_curr="$ts_prev:$ts_test_file"
-    ts_test_files="${ts_test_files:-$0}
-$ts_curr
-"
-    . "$ts_test_file"
-    ts_curr="$ts_prev"
+    # a zero exit status is considered a pass, otherwise fail
+    if [ $? -eq 0 ]; then
+      if [ -e "$TS_TEST_DIR"/skip ]; then
+        ts_status=S
+      else
+        ts_status=P
+      fi
+    else
+      ts_status=F
+      touch "$ts_case_dir"/fail
+    fi
+    echo "$ts_status [$ts_test_desc] $ts_test_name"
   done
+
+  local ts_result=0
+  if [ -e "$ts_case_dir"/fail ]; then
+    ts_result=1
+  fi
+  if ! [ "$TS_KEEP_TMP_DIR" ]; then
+    rm -r "$ts_case_dir"
+  fi
+  return $ts_result
 }
 
 ts_run_test_files () {
   export TS_USR_DIR
   export TS_TMP_DIR
-
-  export TS_COLOR
-  export TS_FILTER
-  export TS_MODE
+  export TS_KEEP_TMP_DIR
   export TS_DEBUG
+  export TS_VERBOSE
 
-  for ts_test_file in "$@"
-  do
-    if [ -f "$ts_test_file" ]
-    then
-      if [ -x "$ts_test_file" ]
-      then
-        if [ x"${ts_test_file}" = x"${ts_test_file#*/}" ]
-        then ./"$ts_test_file" -w
-        else "$ts_test_file" -w
+  for ts_test_file in "$@"; do
+    if [ -f "$ts_test_file" ]; then
+      if [ -x "$ts_test_file" ]; then
+        if [ "${ts_test_file}" = "${ts_test_file#*/}" ]; then
+          ./"$ts_test_file"
+        else
+          "$ts_test_file"
         fi
-      else printf "[%s] not executable\nS 0\n\n" "$ts_test_file"
+      else
+        echo "S [$ts_test_file] not executable"
       fi
-    elif [ x- = x"$ts_test_file" ]
-    then cat
-    else printf "[%s] not a file\nS 0\n\n" "$ts_test_file"
+    else
+      echo "S [$ts_test_file] not a file"
     fi
-  done | ts_report
+  done
 }
 
-ts_function_exists () {
-  [ x"$(command -v "$1" 2>/dev/null)" = x"$1" ]
-}
-
-############################################################################
 # public functions
+###############################################################################
 
-if ! ts_function_exists setup
-then
-setup () {
-  true
-}
+if ! type "setup" &>/dev/null; then
+setup () { :; }
 fi
 
-if ! ts_function_exists teardown
-then
-teardown () {
-  true
-}
+if ! type "teardown" &>/dev/null; then
+teardown () { :; }
 fi
 
 # Flunks unless the numbers $1 (expected) and $2 (actual) are the same.
 assert_status () {
-  ts_expected=$1; ts_actual=$2
-
-  if ! [ $ts_actual -eq $ts_expected ]
-  then
+  local ts_expected=$1
+  local ts_actual=$2
+  local ts_msg
+  if ! [ $ts_actual -eq $ts_expected ]; then
     shift 2
-    if [ $# -ne 0 ]
-    then ts_msg=" ($*)"
+    if [ $# -ne 0 ]; then
+      ts_msg=" ($*)"
     fi
-    printf "expected status %s but was %s%s\n" "$ts_expected" "$ts_actual" "${ts_msg:-}"
+    echo "expected status $ts_expected but was $ts_actual$ts_msg" >&2
     exit 1
   fi
 }
@@ -435,48 +182,30 @@ assert_status () {
 # Flunks unless the variables $1 (expected) and $2 (actual) are the same.
 # Reads from stdin for '-'.  '-' is assumed if $2 is not specified.
 assert_output () {
-  ts_expected="$1"; ts_actual="${2:--}"
-
-  if [ x- = x"$ts_expected" ]
-  then
-    ts_expected=$(cat; printf x)
-    ts_expected=${ts_expected%x}
+  local ts_expected="$1"
+  local ts_actual="${2:--}"
+  if [ "$ts_expected" = - ]; then
+    ts_expected=$(cat)
   fi
-
-  if [ x- = x"$ts_actual" ]
-  then
-    ts_actual=$(cat; printf x)
-    ts_actual=${ts_actual%x}
+  if [ "$ts_actual" = - ]; then
+    ts_actual=$(cat)
   fi
-
-  if [ x"$ts_actual" != x"$ts_expected" ]
-  then
-    mkdir -p "$(dirname "$ts_test_dir")"
-    printf "%s" "$ts_expected" > "$ts_test_dir.e.txt"
-    printf "%s" "$ts_actual"   > "$ts_test_dir.a.txt"
-    printf "unequal output:\n"
-
-    ${TS_DIFF:-diff} "$ts_test_dir.e.txt" "$ts_test_dir.a.txt"
-
+  if [ "$ts_actual" != "$ts_expected" ]; then
     return 1
   fi
 }
 
 skip () {
-  ts_reason="${1:-no reason given}"
-
-  touch "$ts_skip_file"
-  printf "%s\n" "$ts_reason"
-
+  local ts_reason="$1"
+  printf "$ts_reason\n" > "$TS_TEST_DIR"/skip
   exit 0
 }
 
-############################################################################
+# Run the given test files or this script as single suite.
+###############################################################################
 
-# Run the test files if this script is executed directly.
-if [ ts = "$ts_progname" ]
-then ts_run_test_files "$@"
-elif [ "." = "$1" ]
-then ts_src_test_files "$@"
-else ts_run_test_suite "$@"
+if [ ts = "$ts_progname" ]; then
+  ts_run_test_files "$@"
+else
+  ts_run_test_suite "$@"
 fi
